apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: earthquake-demo
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        serviceAccountName: build-bot
        source:
          git:
            url: https://github.com/gswk/earthquake-demo-frontend.git
            revision: flood
        template:
          name: buildpack
          arguments:
          - name: IMAGE
            value: docker.io/gswk/earthquake-demo-frontend:flood
      revisionTemplate:
        spec:
          container:
            image: docker.io/gswk/earthquake-demo-frontend:flood
            env:
            - name: EVENTS_API
              value: "http://geocoder.default.svc.cluster.local"